// New-template copy only. The original portfolio's wording is unchanged.
// Grounding: existing portfolio records/essay and Chief's WORK, LIFE, BEAUTY principles.
// Research descriptions describe proposals, not independently verified outcomes.
export const COPY = {
  en: {
    title: 'I build to understand.',
    intro: 'I build software, study how systems reason, and make photographs.',
    role: 'Designer, photographer, researcher.',
    entryWelcome: 'Welcome', entryDescription: 'Good day. Welcome.', entrySkip: 'Skip introduction',
    work: 'Selected work', research: 'Research', photography: 'Photography', about: 'About', contact: 'Contact',
    notesHeading: 'Notes', backPortfolio: 'Back to portfolio', noteLanguage: 'Written in English',
    approachHeading: 'My approach', principles: 'Working principles',
    viewLabel: 'Portfolio view', guiLabel: 'Visual view',
    devLabel: 'Dev Mode', devTitle: 'Rhine / Dev Mode', devBack: 'Return to GUI', devRun: 'Run',
    devBoundary: 'A command view of this portfolio. Browser only—no shell, filesystem, or system access.',
    devIntro: 'Explore the same work in a different way. Start with help, or choose a command below.',
    devInput: 'Portfolio command', devResults: 'Command results', devHint: 'Enter runs · ↑ ↓ history · Escape returns to GUI. Tab moves between controls.',
    devEmpty: 'No matches. Try ls, or search with a shorter name.', devUnknown: 'Not a portfolio command. Type help for the available commands.',
    devUsage: 'Use ls [work|research|albums], find <text>, open <id>, or theme light|dark.', devUnavailable: 'In development—no public link yet.',
    devHelp: ['help — show these commands', 'ls [work|research|albums] — list content and IDs', 'find <text> — search names and descriptions', 'open <id> — show a source link or open an album/reading page', 'theme light|dark — change this site’s theme', 'clear — clear the visible transcript', 'exit — return to GUI without losing your place'],

    workIntro: 'Tools for reasoning, research, and careful software work.',
    researchIntro: 'Ideas put into writing so they can be examined, tested, and revised.',
    photoIntro: 'Photography teaches me what to notice—and what to leave out.',
    aboutBody: 'I’m Rhine, a designer, photographer, and researcher based in the Philippines. I build to make a question concrete, then test what I thought I understood.',
    purpose: 'I want the systems I build to show their evidence, name their limits, and remain open to correction.',
    notes: 'Notes from building, reading, and learning to see.',
    contactBody: 'For research, software, or photography—tell me what you’re working on.',
    viewWork: 'Explore the work', viewAlbum: 'View album', allAlbums: 'All albums',
    readNote: 'Read the note', fullPurpose: 'More on my approach', email: 'Email me', skip: 'Skip to content',
    light: 'Light', dark: 'Dark', theme: 'Colour theme', noScript: 'You’re viewing the English edition. Language and theme controls need JavaScript.',
    heroAlt: 'Snow-covered mountains across a lake, framed by autumn leaves in Switzerland.',
    imageError: 'This photograph could not be loaded.', imageLoading: 'Loading photograph…', previewImage: 'Preview photograph', openImage: 'Open image', photoNumber: 'Photograph',
    projects: [
      'Tools for testing hypotheses, interventions, and counterfactuals.',
      'A companion-agent runtime for sustained work, memory, and explanation.',
      'A terminal workspace for AI-assisted software work.',
      'A place to explore interface motion and landing-page templates.',
      'A seismic observation interface that keeps events and reports distinct.',
    ],
    papers: [
      'A proposal for constraining unsafe reasoning before an agent uses a tool.',
      'A model exploring how ongoing affective feedback could guide intelligence.',
      'A method combining causal reasoning, memory, and critique.',
      'An examination of school violence in the Philippines beyond single-cause blame.',
    ],
    claim: 'Keep evidence, uncertainty, and limits visible.',
  },
  de: {
    title: 'Ich baue, um zu verstehen.',
    intro: 'Ich entwickle Software, untersuche, wie Systeme schlussfolgern, und fotografiere.',
    role: 'Designer, Fotograf, Forscher.',
    entryWelcome: 'Willkommen', entryDescription: 'Guten Tag. Willkommen.', entrySkip: 'Einleitung überspringen',
    work: 'Ausgewählte Arbeiten', research: 'Forschung', photography: 'Fotografie', about: 'Über mich', contact: 'Kontakt',
    notesHeading: 'Notizen', backPortfolio: 'Zurück zum Portfolio', noteLanguage: 'Auf Englisch verfasst',
    approachHeading: 'Mein Ansatz', principles: 'Arbeitsprinzipien',
    viewLabel: 'Portfolio-Ansicht', guiLabel: 'Visuelle Ansicht',
    devLabel: 'Entwicklermodus', devTitle: 'Rhine / Dev Mode', devBack: 'Zurück zur GUI', devRun: 'Ausführen',
    devBoundary: 'Eine Befehlsansicht dieses Portfolios. Nur im Browser—kein Zugriff auf Shell, Dateisystem oder Betriebssystem.',
    devIntro: 'Dieselben Arbeiten, anders erkundet. Beginne mit help oder wähle unten einen Befehl.',
    devInput: 'Portfolio-Befehl', devResults: 'Befehlsergebnisse', devHint: 'Enter führt aus · ↑ ↓ Verlauf · Escape zurück zur GUI. Tab wechselt zwischen den Bedienelementen.',
    devEmpty: 'Keine Treffer. Versuche ls oder suche mit einem kürzeren Namen.', devUnknown: 'Kein Portfolio-Befehl. help zeigt die verfügbaren Befehle.',
    devUsage: 'Nutze ls [work|research|albums], find <Text>, open <ID> oder theme light|dark.', devUnavailable: 'In Entwicklung—noch kein öffentlicher Link.',
    devHelp: ['help — Befehle anzeigen', 'ls [work|research|albums] — Inhalte und IDs auflisten', 'find <Text> — Namen und Beschreibungen durchsuchen', 'open <ID> — Quelllink anzeigen oder Album/Leseseite öffnen', 'theme light|dark — Farbschema dieser Website ändern', 'clear — sichtbaren Verlauf leeren', 'exit — zur GUI zurückkehren, ohne die Position zu verlieren'],

    workIntro: 'Werkzeuge für Schlussfolgerungen, Forschung und sorgfältige Softwarearbeit.',
    researchIntro: 'Ideen, aufgeschrieben, damit sie geprüft, getestet und überarbeitet werden können.',
    photoIntro: 'Fotografie lehrt mich, was ich beachten und was ich weglassen sollte.',
    aboutBody: 'Ich bin Rhine, Designer, Fotograf und Forscher auf den Philippinen. Ich baue, um eine Frage greifbar zu machen, und prüfe dann, was ich verstanden zu haben glaubte.',
    purpose: 'Die Systeme, die ich baue, sollen ihre Belege zeigen, ihre Grenzen benennen und für Korrekturen offen bleiben.',
    notes: 'Notizen vom Bauen, Lesen und Sehenlernen.',
    contactBody: 'Ob Forschung, Software oder Fotografie—erzähle mir, woran du arbeitest.',
    viewWork: 'Arbeiten ansehen', viewAlbum: 'Album ansehen', allAlbums: 'Alle Alben',
    readNote: 'Notiz lesen', fullPurpose: 'Mehr zu meinem Ansatz', email: 'E-Mail schreiben', skip: 'Zum Inhalt',
    light: 'Hell', dark: 'Dunkel', theme: 'Farbschema', noScript: 'Du siehst die englische Ausgabe. Sprach- und Farbauswahl benötigen JavaScript.',
    heroAlt: 'Schneebedeckte Berge hinter einem See, eingerahmt von Herbstlaub in der Schweiz.',
    imageError: 'Dieses Foto konnte nicht geladen werden.', imageLoading: 'Foto wird geladen…', previewImage: 'Foto in der Vorschau ansehen', openImage: 'Bild öffnen', photoNumber: 'Foto',
    projects: [
      'Werkzeuge zum Prüfen von Hypothesen, Interventionen und kontrafaktischen Szenarien.',
      'Eine Laufzeit für Begleitagenten, mit Kontinuität, Gedächtnis und Erklärungen.',
      'Ein Terminal-Arbeitsbereich für KI-gestützte Softwareentwicklung.',
      'Ein Ort für Interface-Bewegung und Landingpage-Vorlagen.',
      'Eine Oberfläche für seismische Beobachtungen, die Ereignisse und Berichte getrennt hält.',
    ],
    papers: [
      'Ein Vorschlag, unsichere Schlussfolgerungen vor dem Werkzeugeinsatz eines Agenten zu begrenzen.',
      'Ein Modell dazu, wie fortlaufende affektive Rückmeldung Intelligenz steuern könnte.',
      'Eine Methode, die kausales Denken, Gedächtnis und Kritik verbindet.',
      'Eine Untersuchung von Schulgewalt auf den Philippinen jenseits monokausaler Schuldzuweisungen.',
    ],
    claim: 'Belege, Unsicherheit und Grenzen sichtbar halten.',
  },
  fr: {
    title: 'Je construis pour comprendre.',
    intro: 'Je développe des logiciels, étudie le raisonnement des systèmes et fais des photographies.',
    role: 'Designer, photographe, chercheur.',
    entryWelcome: 'Bienvenue', entryDescription: 'Bonjour. Bienvenue.', entrySkip: 'Passer l’introduction',
    work: 'Projets choisis', research: 'Recherche', photography: 'Photographie', about: 'À propos', contact: 'Contact',
    notesHeading: 'Notes', backPortfolio: 'Retour au portfolio', noteLanguage: 'Écrit en anglais',
    approachHeading: 'Ma démarche', principles: 'Principes de travail',
    viewLabel: 'Vue du portfolio', guiLabel: 'Vue visuelle',
    devLabel: 'Mode développeur', devTitle: 'Rhine / Dev Mode', devBack: 'Retour à la GUI', devRun: 'Exécuter',
    devBoundary: 'Une vue par commandes de ce portfolio. Dans le navigateur uniquement—sans accès au shell, aux fichiers ni au système.',
    devIntro: 'Les mêmes projets, une autre façon de les explorer. Commencez par help ou choisissez une commande ci-dessous.',
    devInput: 'Commande du portfolio', devResults: 'Résultats des commandes', devHint: 'Entrée exécute · ↑ ↓ historique · Échap revient à la GUI. Tab passe entre les contrôles.',
    devEmpty: 'Aucun résultat. Essayez ls ou recherchez un nom plus court.', devUnknown: 'Ce n’est pas une commande du portfolio. Tapez help pour voir les commandes.',
    devUsage: 'Utilisez ls [work|research|albums], find <texte>, open <id> ou theme light|dark.', devUnavailable: 'En développement—pas encore de lien public.',
    devHelp: ['help — afficher les commandes', 'ls [work|research|albums] — lister les contenus et identifiants', 'find <texte> — rechercher noms et descriptions', 'open <id> — afficher un lien source ou ouvrir un album/une page de lecture', 'theme light|dark — changer le thème du site', 'clear — effacer la transcription visible', 'exit — revenir à la GUI sans perdre sa position'],

    workIntro: 'Des outils pour raisonner, chercher et développer avec soin.',
    researchIntro: 'Des idées mises par écrit pour être examinées, testées et révisées.',
    photoIntro: 'La photographie m’apprend ce qu’il faut remarquer et ce qu’il faut laisser de côté.',
    aboutBody: 'Je suis Rhine, designer, photographe et chercheur aux Philippines. Je construis pour rendre une question concrète, puis je teste ce que je croyais avoir compris.',
    purpose: 'Je veux que les systèmes que je construis montrent leurs preuves, nomment leurs limites et restent ouverts à la correction.',
    notes: 'Notes de construction, de lecture et d’apprentissage du regard.',
    contactBody: 'Recherche, logiciel ou photographie—parlez-moi de ce sur quoi vous travaillez.',
    viewWork: 'Voir les projets', viewAlbum: 'Voir l’album', allAlbums: 'Tous les albums',
    readNote: 'Lire la note', fullPurpose: 'Ma démarche', email: 'M’écrire', skip: 'Aller au contenu',
    light: 'Clair', dark: 'Sombre', theme: 'Thème de couleur', noScript: 'Vous consultez l’édition anglaise. Les commandes de langue et de thème nécessitent JavaScript.',
    heroAlt: 'Des montagnes enneigées au-delà d’un lac, encadrées de feuillage d’automne en Suisse.',
    imageError: 'Cette photographie n’a pas pu être chargée.', imageLoading: 'Chargement de la photographie…', previewImage: 'Aperçu de la photographie', openImage: 'Ouvrir l’image', photoNumber: 'Photographie',
    projects: [
      'Des outils pour tester hypothèses, interventions et scénarios contrefactuels.',
      'Un environnement d’agents compagnons pour un travail suivi, la mémoire et l’explication.',
      'Un espace de travail en terminal pour le développement assisté par IA.',
      'Un lieu d’exploration du mouvement des interfaces et des modèles de pages d’accueil.',
      'Une interface d’observation sismique qui distingue les événements des témoignages.',
    ],
    papers: [
      'Une proposition pour limiter les raisonnements dangereux avant qu’un agent utilise un outil.',
      'Un modèle explorant comment un retour affectif continu pourrait guider l’intelligence.',
      'Une méthode associant raisonnement causal, mémoire et critique.',
      'Une étude de la violence scolaire aux Philippines au-delà d’une cause unique.',
    ],
    claim: 'Garder les preuves, l’incertitude et les limites visibles.',
  },
  it: {
    title: 'Costruisco per capire.',
    intro: 'Sviluppo software, studio come ragionano i sistemi e fotografo.',
    role: 'Designer, fotografo, ricercatore.',
    entryWelcome: 'Benvenuto', entryDescription: 'Buona giornata. Benvenuto.', entrySkip: 'Salta l’introduzione',
    work: 'Lavori selezionati', research: 'Ricerca', photography: 'Fotografia', about: 'Chi sono', contact: 'Contatti',
    notesHeading: 'Appunti', backPortfolio: 'Torna al portfolio', noteLanguage: 'Scritto in inglese',
    approachHeading: 'Il mio approccio', principles: 'Principi di lavoro',
    viewLabel: 'Vista del portfolio', guiLabel: 'Vista visiva',
    devLabel: 'Modalità sviluppatore', devTitle: 'Rhine / Dev Mode', devBack: 'Torna alla GUI', devRun: 'Esegui',
    devBoundary: 'Una vista a comandi di questo portfolio. Solo nel browser—nessun accesso a shell, file o sistema.',
    devIntro: 'Gli stessi lavori, un altro modo di esplorarli. Inizia con help o scegli un comando qui sotto.',
    devInput: 'Comando del portfolio', devResults: 'Risultati dei comandi', devHint: 'Invio esegue · ↑ ↓ cronologia · Escape torna alla GUI. Tab passa tra i controlli.',
    devEmpty: 'Nessun risultato. Prova ls o cerca un nome più breve.', devUnknown: 'Non è un comando del portfolio. Digita help per i comandi disponibili.',
    devUsage: 'Usa ls [work|research|albums], find <testo>, open <id> o theme light|dark.', devUnavailable: 'In sviluppo—nessun link pubblico per ora.',
    devHelp: ['help — mostra i comandi', 'ls [work|research|albums] — elenca contenuti e ID', 'find <testo> — cerca nomi e descrizioni', 'open <id> — mostra un link fonte o apri un album/una pagina di lettura', 'theme light|dark — cambia il tema del sito', 'clear — cancella la trascrizione visibile', 'exit — torna alla GUI senza perdere la posizione'],

    workIntro: 'Strumenti per ragionare, fare ricerca e sviluppare software con cura.',
    researchIntro: 'Idee messe per iscritto perché possano essere esaminate, testate e riviste.',
    photoIntro: 'La fotografia mi insegna cosa notare e cosa lasciare fuori.',
    aboutBody: 'Sono Rhine, designer, fotografo e ricercatore nelle Filippine. Costruisco per rendere concreta una domanda, poi verifico ciò che pensavo di aver capito.',
    purpose: 'Voglio che i sistemi che costruisco mostrino le prove, dichiarino i limiti e restino aperti alle correzioni.',
    notes: 'Appunti dal costruire, leggere e imparare a vedere.',
    contactBody: 'Ricerca, software o fotografia—raccontami a cosa stai lavorando.',
    viewWork: 'Esplora i lavori', viewAlbum: 'Vedi l’album', allAlbums: 'Tutti gli album',
    readNote: 'Leggi l’appunto', fullPurpose: 'Il mio approccio', email: 'Scrivimi', skip: 'Vai al contenuto',
    light: 'Chiaro', dark: 'Scuro', theme: 'Tema colore', noScript: 'Stai vedendo l’edizione inglese. I controlli di lingua e tema richiedono JavaScript.',
    heroAlt: 'Montagne innevate oltre un lago, incorniciate da foglie autunnali in Svizzera.',
    imageError: 'Non è stato possibile caricare questa fotografia.', imageLoading: 'Caricamento della fotografia…', previewImage: 'Anteprima della fotografia', openImage: 'Apri l’immagine', photoNumber: 'Fotografia',
    projects: [
      'Strumenti per verificare ipotesi, interventi e scenari controfattuali.',
      'Un runtime di agenti compagni per lavoro continuativo, memoria e spiegazione.',
      'Uno spazio di lavoro nel terminale per lo sviluppo assistito dall’IA.',
      'Uno spazio per esplorare il movimento delle interfacce e i modelli di landing page.',
      'Un’interfaccia di osservazione sismica che distingue gli eventi dalle segnalazioni.',
    ],
    papers: [
      'Una proposta per limitare ragionamenti pericolosi prima che un agente usi uno strumento.',
      'Un modello che esplora come un feedback affettivo continuo possa guidare l’intelligenza.',
      'Un metodo che unisce ragionamento causale, memoria e critica.',
      'Uno studio sulla violenza scolastica nelle Filippine oltre le spiegazioni monocausali.',
    ],
    claim: 'Mantenere visibili prove, incertezza e limiti.',
  },
  zh: {
    title: '在构建中理解。',
    intro: '我开发软件，研究系统如何推理，也拍摄照片。',
    role: '设计师、摄影师、研究者。',
    entryWelcome: '欢迎', entryDescription: '你好，欢迎。', entrySkip: '跳过开场',
    work: '精选项目', research: '研究', photography: '摄影', about: '关于', contact: '联系',
    notesHeading: '笔记', backPortfolio: '返回作品集', noteLanguage: '以英文写作',
    approachHeading: '我的方法', principles: '工作原则',
    viewLabel: '作品集视图', guiLabel: '视觉视图',
    devLabel: '开发者模式', devTitle: 'Rhine / Dev Mode', devBack: '返回 GUI', devRun: '运行',
    devBoundary: '作品集的命令视图。仅在浏览器内运行，不能访问终端、文件系统或操作系统。',
    devIntro: '用另一种方式浏览同样的作品。输入 help，或选择下方的命令。',
    devInput: '作品集命令', devResults: '命令结果', devHint: 'Enter 运行 · ↑ ↓ 历史 · Escape 返回 GUI。Tab 在控件间移动。',
    devEmpty: '没有匹配项。试试 ls，或搜索更短的名称。', devUnknown: '这不是作品集命令。输入 help 查看可用命令。',
    devUsage: '使用 ls [work|research|albums]、find <文字>、open <id> 或 theme light|dark。', devUnavailable: '开发中，暂未提供公开链接。',
    devHelp: ['help — 显示命令', 'ls [work|research|albums] — 列出内容和 ID', 'find <文字> — 搜索名称与描述', 'open <id> — 显示来源链接或打开相册、阅读页面', 'theme light|dark — 更改本网站主题', 'clear — 清空可见记录', 'exit — 返回 GUI 并保留浏览位置'],

    workIntro: '为推理、研究和严谨的软件开发而做的工具。',
    researchIntro: '把想法写下来，让它们能够被审视、检验和修正。',
    photoIntro: '摄影教我留意什么，也教我舍去什么。',
    aboutBody: '我是 Rhine，常驻菲律宾的设计师、摄影师与研究者。我通过构建把问题变得具体，再检验自己以为已经理解的东西。',
    purpose: '我希望自己构建的系统能展示依据、说明局限，并始终允许纠正。',
    notes: '来自构建、阅读与学习观察的笔记。',
    contactBody: '研究、软件或摄影——欢迎告诉我你正在做什么。',
    viewWork: '查看项目', viewAlbum: '查看相册', allAlbums: '全部相册',
    readNote: '阅读笔记', fullPurpose: '了解我的方法', email: '给我写信', skip: '跳至正文',
    light: '浅色', dark: '深色', theme: '颜色主题', noScript: '当前为英文版。语言和主题切换需要 JavaScript。',
    heroAlt: '瑞士秋叶环绕的湖面与远处的雪山。',
    imageError: '这张照片未能加载。', imageLoading: '正在加载照片…', previewImage: '预览照片', openImage: '打开图片', photoNumber: '照片',
    projects: [
      '用于检验假设、干预与反事实的工具。',
      '支持持续工作、记忆与解释的陪伴智能体运行时。',
      '用于 AI 辅助软件开发的终端工作空间。',
      '探索界面动效与落地页模板的空间。',
      '区分地震事件与感知报告的观测界面。',
    ],
    papers: [
      '关于在智能体调用工具之前约束不安全推理的提案。',
      '探索持续情感反馈如何引导智能的模型。',
      '结合因果推理、记忆与批判的方法。',
      '超越单一归因，审视菲律宾校园暴力。',
    ],
    claim: '让依据、不确定性与局限保持可见。',
  },
};

export function copyFor(locale) {
  return COPY[locale] || COPY.en;
}
